[build]
  base = "frontend"
  command = "rm -rf node_modules && npm install --legacy-peer-deps --no-audit --no-fund --include=optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.1"
